In [1]:
# imports:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [3]:
# steps and line-spaces
arr = np.arange(10, 20)
print(arr)

step = np.arange(10, 30, 2)
print(step)

linespace = np.linspace(10, 30, 5)
print(linespace)


[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18 20 22 24 26 28]
[10. 15. 20. 25. 30.]


In [4]:
# Argmax and Argmin ----> gives index
arr = np.array([10, 30, 25, 11, 67, 91, 15, 12, 21])
print(arr.argmax(), arr.argmin())

5 0


In [5]:
# n-dim:
_2d = np.array([[10,20,30,40,50],
                [61,72,38,19,10],
                [11,12,13,14,15]])

print(_2d)


[[10 20 30 40 50]
 [61 72 38 19 10]
 [11 12 13 14 15]]


In [6]:
# reshaping 1d to nd:
array = np.arange(0,16)
_2d = array.reshape(4,4)
_3d = array.reshape(2,4,2)

print(_2d)
print("\n")
print(_3d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [7]:
# Generaring random values:

arr = np.random.rand(5)
print(arr)

arr2 = np.random.randn(2,3)
print(arr2)

[0.84817113 0.7278782  0.68711121 0.64986719 0.51917069]
[[-1.01400995 -0.62935905 -0.48656564]
 [-1.18990683  0.58277598 -1.03175258]]


In [8]:
print(np.log(arr))
print(np.sqrt(arr))
print(np.abs(-10))

[-0.16467285 -0.31762156 -0.37525912 -0.43098727 -0.65552257]
[0.92096207 0.85315778 0.82892172 0.8061434  0.720535  ]
10
