## Creating a ANN - Classification model used to predict iris species

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('DataSets/Iris.csv')
df.head(2)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

#### Data preprocessing

In [3]:
df.isnull().all().sum()

0

In [4]:
df.Species.value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

#### Encoding - Species

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
print(df.Species.unique())
df['Species'] = le.fit_transform(df['Species'])
print(df.Species.unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[0 1 2]


#### Splitting Data 

In [6]:
# x and y:

x = df.iloc[:,1:5]
y = df.iloc[:,5:6]
print(x.head(2))
print(y.head(2))

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
   Species
0        0
1        0


In [7]:
# train and test:

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=10)

xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((120, 4), (30, 4), (120, 1), (30, 1))

#### Creating ANN model:

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

C:\Users\Jayanth\AppData\Roaming\Python\Python310\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "


In [9]:
model = Sequential()

In [10]:
model.add(Dense(4, activation='relu'))

model.add(Dense(27, activation='relu'))
model.add(Dense(81, activation='relu'))
model.add(Dense(135, activation='relu'))

model.add(Dense(3, activation='softmax'))

In [11]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [12]:
model.fit(xtrain, ytrain,batch_size=5 ,epochs=20, validation_data=(xtest, ytest))

Epoch 1/20
24/24 [==============================] - 1s 9ms/step - loss: 1.0125 - accuracy: 0.3417 - val_loss: 0.9831 - val_accuracy: 0.5333
Epoch 2/20
24/24 [==============================] - 0s 4ms/step - loss: 0.8930 - accuracy: 0.6917 - val_loss: 0.9111 - val_accuracy: 0.5333
Epoch 3/20
24/24 [==============================] - 0s 3ms/step - loss: 0.7620 - accuracy: 0.6917 - val_loss: 0.7077 - val_accuracy: 0.5667
Epoch 4/20
24/24 [==============================] - 0s 3ms/step - loss: 0.6180 - accuracy: 0.7417 - val_loss: 0.5751 - val_accuracy: 0.5667
Epoch 5/20
24/24 [==============================] - 0s 2ms/step - loss: 0.5023 - accuracy: 0.7167 - val_loss: 0.4631 - val_accuracy: 0.7667
Epoch 6/20
24/24 [==============================] - 0s 5ms/step - loss: 0.4661 - accuracy: 0.7250 - val_loss: 0.4212 - val_accuracy: 0.9667
Epoch 7/20
24/24 [==============================] - 0s 3ms/step - loss: 0.3835 - accuracy: 0.8000 - val_loss: 0.3924 - val_accuracy: 0.9667
Epoch 8/20
24/24 [==

In [13]:
model.save('Models/iris-pred.h5')

In [16]:
# pred-new:

pred = model.predict([[2.1, 7.5, 4.2,0.5]])
print(pred)

max = np.argmax(pred)
output = ['Iris-setosa','Iris-versicolor','Iris-virginica']
output[max]

[[9.8870414e-01 1.1295447e-02 3.0926273e-07]]


'Iris-setosa'

In [15]:
pred = model.predict([[2.5,4.34,5.3,1.3]])
print(pred)

max = np.argmax(pred)
output = ['Iris-setosa','Iris-versicolor','Iris-virginica']
output[max]

[[5.1558032e-05 1.1725781e-01 8.8269061e-01]]


'Iris-virginica'