## LSTM model

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('DataSets/Stock_Price_Train.csv')
df.head(3)

Date    Open    High     Low   Close     Volume
0  1/3/2012  325.25  332.83  324.97  663.59  7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45  5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21  6,590,300

##### after completing all the preprocessing:

### Step 1: Selecting the column

In [6]:
col = df.iloc[:,1:2].values
col

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

### Step 2: Normalization

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
norm = MinMaxScaler()
col = norm.fit_transform(col)

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

### Step 3 : Splitting the col into test and train

In [9]:
len(col)

1258

In [27]:
xtrain = []
ytrain = []
for i in range(60,len(col)):
    xtrain.append(col[i-60:i,0])
    ytrain.append(col[i,0])
    

### Step 4 : converting list to array

In [28]:
xtrain, ytrain = np.array(xtrain), np.array(ytrain)

In [29]:
xtrain.shape

(1198, 60)

In [32]:
xtrain = np.reshape(xtrain, (1198, 60, 1))
xtrain.shape

(1198, 60, 1)

### Step 5: Building the LSTM model

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

In [34]:
model = Sequential()

model.add(LSTM(50, input_shape=(60,1), return_sequences=True))
model.add(LSTM(35, return_sequences=True))
model.add(LSTM(25, return_sequences=True))

model.add(Dense(1))

In [35]:
model.compile(optimizer='adam', loss='mse')

In [37]:
model.fit(xtrain, ytrain, batch_size=20, epochs=15)

Epoch 1/15
60/60 [==============================] - 2s 36ms/step - loss: 0.0742
Epoch 2/15
60/60 [==============================] - 2s 35ms/step - loss: 0.0750
Epoch 3/15
60/60 [==============================] - 3s 45ms/step - loss: 0.0748
Epoch 4/15
60/60 [==============================] - 3s 46ms/step - loss: 0.0749
Epoch 5/15
60/60 [==============================] - 3s 46ms/step - loss: 0.0749
Epoch 6/15
60/60 [==============================] - 3s 55ms/step - loss: 0.0751
Epoch 7/15
60/60 [==============================] - 3s 55ms/step - loss: 0.0747
Epoch 8/15
60/60 [==============================] - 3s 54ms/step - loss: 0.0748
Epoch 9/15
60/60 [==============================] - 3s 57ms/step - loss: 0.0747
Epoch 10/15
60/60 [==============================] - 3s 55ms/step - loss: 0.0749
Epoch 11/15
60/60 [==============================] - 3s 52ms/step - loss: 0.0748
Epoch 12/15
60/60 [==============================] - 3s 57ms/step - loss: 0.0746
Epoch 13/15
60/60 [==================

In [51]:
model.predict([[0.08497656], [0.08497746], [0.00967334], [0.01642607], [0.02100231], [0.02280676], [0.02273235]])

array([[[0.4236458 ]],

       [[0.42364582]],

       [[0.421433  ]],

       [[0.4216307 ]],

       [[0.42176476]],

       [[0.4218176 ]],

       [[0.42181545]]], dtype=float32)